version: "3.8"
services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
  s3-local-on-minio:
    image: minio/minio
    container_name: s3-local
    ports:
      - "9001:9000"
    command: ["--compat", "server", "/data"]
    restart: always
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: "${AWS_ACCESS_KEY_ID}"
      MINIO_SECRET_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_ACCESS_KEY: "${AWS_ACCESS_KEY_ID}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_S3_ENDPOINT_URL: "${AWS_S3_ENDPOINT_URL}"
      AWS_S3_BUCKET_NAME: "${AWS_S3_BUCKET_NAME}"
